-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.
-- Activa ingresos libres, ganancia real, cortes del día, clientes, pedidos y fiados.

-- 1) Ventas mejoradas: propinas/ingresos libres + costo y ganancia real.
alter table "Ventas"
  add column if not exists concepto text,
  add column if not exists tipo text default 'producto',
  add column if not exists costo_total numeric default 0,
  add column if not exists ganancia numeric default 0;

-- Permite ventas sin producto_id para propinas, anticipos o ingresos libres.
alter table "Ventas" alter column producto_id drop not null;

-- 2) Gastos recurrentes: plantillas reutilizables para costos fijos o unitarios.
create table if not exists "GastosRecurrentes" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  concepto text not null,
  monto numeric not null check (monto >= 0),
  categoria text default 'Producción',
  activo boolean default true
);

-- 3) Cortes diarios: guarda el cierre de cada día.
create table if not exists "CortesDiarios" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  fecha date not null default current_date,
  total_ventas numeric not null default 0,
  ingresos_libres numeric not null default 0,
  gastos numeric not null default 0,
  costo_productos numeric not null default 0,
  ganancia numeric not null default 0,
  productos_vendidos integer not null default 0,
  movimientos integer not null default 0,
  notas text
);

-- 4) Clientes.
create table if not exists "Clientes" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nombre text not null,
  telefono text,
  notas text
);

-- 5) Pedidos, anticipos y fiados.
create table if not exists "Pedidos" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  cliente_id bigint references "Clientes"(id) on delete set null,
  cliente_nombre text not null,
  telefono text,
  detalle text not null,
  total numeric not null check (total >= 0),
  anticipo numeric not null default 0 check (anticipo >= 0),
  saldo numeric not null default 0 check (saldo >= 0),
  fecha_entrega timestamptz,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'en_proceso', 'listo', 'entregado')),
  estado_pago text not null default 'pendiente' check (estado_pago in ('pendiente', 'parcial', 'pagado')),
  notas text
);

create index if not exists idx_pedidos_estado on "Pedidos"(estado);
create index if not exists idx_pedidos_estado_pago on "Pedidos"(estado_pago);
create index if not exists idx_pedidos_fecha_entrega on "Pedidos"(fecha_entrega);
create index if not exists idx_clientes_nombre on "Clientes"(nombre);

-- 6) Seguridad simple para proyectos con Supabase Auth.
alter table "GastosRecurrentes" enable row level security;
alter table "CortesDiarios" enable row level security;
alter table "Clientes" enable row level security;
alter table "Pedidos" enable row level security;

do $$
begin
  -- Gastos recurrentes
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'GastosRecurrentes' and policyname = 'Usuarios autenticados pueden ver gastos recurrentes') then
    create policy "Usuarios autenticados pueden ver gastos recurrentes" on "GastosRecurrentes" for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'GastosRecurrentes' and policyname = 'Usuarios autenticados pueden crear gastos recurrentes') then
    create policy "Usuarios autenticados pueden crear gastos recurrentes" on "GastosRecurrentes" for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'GastosRecurrentes' and policyname = 'Usuarios autenticados pueden borrar gastos recurrentes') then
    create policy "Usuarios autenticados pueden borrar gastos recurrentes" on "GastosRecurrentes" for delete to authenticated using (true);
  end if;

  -- Cortes diarios
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'CortesDiarios' and policyname = 'Usuarios autenticados pueden ver cortes') then
    create policy "Usuarios autenticados pueden ver cortes" on "CortesDiarios" for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'CortesDiarios' and policyname = 'Usuarios autenticados pueden crear cortes') then
    create policy "Usuarios autenticados pueden crear cortes" on "CortesDiarios" for insert to authenticated with check (true);
  end if;

  -- Clientes
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Clientes' and policyname = 'Usuarios autenticados pueden ver clientes') then
    create policy "Usuarios autenticados pueden ver clientes" on "Clientes" for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Clientes' and policyname = 'Usuarios autenticados pueden crear clientes') then
    create policy "Usuarios autenticados pueden crear clientes" on "Clientes" for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Clientes' and policyname = 'Usuarios autenticados pueden actualizar clientes') then
    create policy "Usuarios autenticados pueden actualizar clientes" on "Clientes" for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Clientes' and policyname = 'Usuarios autenticados pueden borrar clientes') then
    create policy "Usuarios autenticados pueden borrar clientes" on "Clientes" for delete to authenticated using (true);
  end if;

  -- Pedidos
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Pedidos' and policyname = 'Usuarios autenticados pueden ver pedidos') then
    create policy "Usuarios autenticados pueden ver pedidos" on "Pedidos" for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Pedidos' and policyname = 'Usuarios autenticados pueden crear pedidos') then
    create policy "Usuarios autenticados pueden crear pedidos" on "Pedidos" for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Pedidos' and policyname = 'Usuarios autenticados pueden actualizar pedidos') then
    create policy "Usuarios autenticados pueden actualizar pedidos" on "Pedidos" for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Pedidos' and policyname = 'Usuarios autenticados pueden borrar pedidos') then
    create policy "Usuarios autenticados pueden borrar pedidos" on "Pedidos" for delete to authenticated using (true);
  end if;
end $$;
